import type { Building } from './types';

type WorkforceRow = [
  id: string,
  name: string,
  workers: number,
  education: Building['education'],
  availableFrom: NonNullable<Building['availableFrom']>,
  category: string,
  dlc?: string
];

const rows: WorkforceRow[] = [
  ['dock','Hafen',6,'uneducated','colonial','Infrastruktur'],
  ['construction-office','Baubüro',6,'uneducated','colonial','Infrastruktur'],
  ['teamster-port','Transporthafen',6,'uneducated','colonial','Infrastruktur'],
  ['power-plant','Kraftwerk',6,'high-school','world-wars','Infrastruktur'],
  ['parking-deck','Parkhaus',1,'uneducated','world-wars','Infrastruktur'],
  ['bus-garage','Busdepot',4,'uneducated','world-wars','Infrastruktur'],
  ['nuclear-power-plant','Atomkraftwerk',4,'college','cold-war','Infrastruktur'],
  ['metro-station','U-Bahn-Station',2,'uneducated','cold-war','Infrastruktur'],
  ['teleferic-station','Seilbahnstation',4,'uneducated','modern','Infrastruktur'],
  ['solar-power-plant','Solarkraftwerk',3,'high-school','modern','Infrastruktur'],
  ['drone-delivery-service','Drohnen-Lieferservice',3,'uneducated','modern','Infrastruktur','caribbean-skies'],
  ['cargo-airport','Frachtflughafen',6,'uneducated','world-wars','Infrastruktur','caribbean-skies'],
  ['drone-taxi','Drohnen-Taxi',3,'college','modern','Infrastruktur','caribbean-skies'],
  ['fusion-reactor','Fusionsreaktor',5,'college','modern','Infrastruktur','new-frontiers'],
  ['lighthouse','Leuchtturm',1,'uneducated','colonial','Infrastruktur','tropican-shores'],
  ['tidal-power-station','Gezeitenkraftwerk',4,'high-school','cold-war','Infrastruktur','tropican-shores'],
  ['manure-spreader','Miststreuer',3,'uneducated','colonial','Landwirtschaft'],
  ['agriculture-tower','Landwirtschaftsturm',4,'high-school','modern','Landwirtschaft','new-frontiers'],
  ['synthetic-food-lab','Labor für synthetische Nahrung',4,'high-school','modern','Landwirtschaft','new-frontiers'],
  ['drone-factory','Drohnenfabrik',8,'uneducated','modern','Industrie','caribbean-skies'],
  ['battery-plant','Batteriefabrik',10,'uneducated','modern','Industrie','caribbean-skies'],
  ['mask-factory','Maskenfabrik',6,'uneducated','world-wars','Industrie','going-viral'],

  ['tavern','Taverne',3,'uneducated','colonial','Unterhaltung'],
  ['circus','Zirkus',6,'uneducated','colonial','Unterhaltung'],
  ['busker','Straßenkünstler',1,'uneducated','colonial','Unterhaltung'],
  ['botanical-garden','Botanischer Garten',2,'uneducated','world-wars','Unterhaltung'],
  ['funfair-pier','Vergnügungspier',6,'uneducated','world-wars','Unterhaltung'],
  ['restaurant','Restaurant',4,'uneducated','world-wars','Unterhaltung'],
  ['arcade','Spielhalle',3,'uneducated','cold-war','Unterhaltung'],
  ['fast-food-joint','Fastfood-Restaurant',4,'uneducated','cold-war','Unterhaltung'],
  ['fourth-dungeon-entrance','Vierter Verlieseingang',3,'uneducated','cold-war','Unterhaltung'],
  ['movie-theater','Kino',4,'uneducated','cold-war','Unterhaltung'],
  ['aqua-park','Wasserpark',3,'uneducated','modern','Unterhaltung'],
  ['rollercoaster','Achterbahn',3,'uneducated','modern','Unterhaltung'],
  ['stadium','Stadion',12,'uneducated','modern','Unterhaltung'],
  ['dance-school','Tanzschule',3,'uneducated','colonial','Unterhaltung','festival'],
  ['festival-grounds','Festivalgelände',4,'uneducated','colonial','Unterhaltung','festival'],
  ['party-blimps','Party-Luftschiffe',4,'uneducated','world-wars','Unterhaltung','festival'],
  ['concert-stage','Konzertbühne',4,'high-school','cold-war','Unterhaltung','festival'],
  ['broadcast-tower','Sendeturm',4,'college','modern','Unterhaltung','festival'],
  ['hologram-funhouse','Hologramm-Spaßhaus',4,'high-school','modern','Unterhaltung','new-frontiers'],
  ['floating-restaurant','Schwimmendes Restaurant',5,'uneducated','world-wars','Unterhaltung','tropican-shores'],
  ['submarine-tours','U-Boot-Touren',4,'high-school','cold-war','Unterhaltung','tropican-shores'],
  ['climbing-park','Kletterpark',5,'uneducated','world-wars','Unterhaltung','return-to-nature'],

  ['theater','Theater',6,'high-school','colonial','Luxusunterhaltung'],
  ['opera-house','Opernhaus',8,'high-school','colonial','Luxusunterhaltung'],
  ['cabaret','Kabarett',4,'high-school','world-wars','Luxusunterhaltung'],
  ['el-presidente-club','El-Presidente-Club',2,'uneducated','world-wars','Luxusunterhaltung','lobbyistico'],
  ['casino','Kasino',6,'high-school','cold-war','Luxusunterhaltung'],
  ['cocktail-bar','Cocktailbar',3,'uneducated','cold-war','Luxusunterhaltung'],
  ['golf-course','Golfplatz',4,'uneducated','cold-war','Luxusunterhaltung'],
  ['gourmet-restaurant','Gourmetrestaurant',6,'high-school','cold-war','Luxusunterhaltung'],
  ['night-club','Nachtclub',4,'uneducated','cold-war','Luxusunterhaltung'],
  ['snorkel-bay','Schnorchelbucht',4,'high-school','cold-war','Luxusunterhaltung'],
  ['beach-resort','Strandresort',4,'uneducated','modern','Luxusunterhaltung'],
  ['hang-gliding','Drachenfliegen',2,'uneducated','modern','Luxusunterhaltung'],
  ['museum-modern-art','Museum für moderne Kunst',4,'college','modern','Luxusunterhaltung'],
  ['yacht-club','Jachtclub',4,'uneducated','modern','Luxusunterhaltung'],
  ['tropitanic','Tropitanic',6,'uneducated','world-wars','Luxusunterhaltung','tropican-shores'],
  ['golden-pearl','Die Goldene Perle',8,'high-school','cold-war','Luxusunterhaltung','tropican-shores'],
  ['yachtlantis','Jachtlantis',10,'college','modern','Luxusunterhaltung','tropican-shores'],

  ['newspaper','Zeitung',4,'high-school','colonial','Medien und Bildung'],
  ['library','Bibliothek',3,'high-school','colonial','Medien und Bildung'],
  ['high-school','Oberschule',4,'high-school','world-wars','Medien und Bildung'],
  ['college','Hochschule',3,'college','world-wars','Medien und Bildung'],
  ['radio-station','Radiosender',2,'high-school','world-wars','Medien und Bildung'],
  ['childhood-museum','Kindheitsmuseum',4,'high-school','cold-war','Medien und Bildung'],
  ['mausoleum','Mausoleum',4,'high-school','cold-war','Medien und Bildung'],
  ['tv-station','Fernsehsender',4,'high-school','cold-war','Medien und Bildung'],
  ['research-lab','Forschungslabor',5,'college','cold-war','Medien und Bildung'],
  ['space-program','Raumfahrtprogramm',10,'college','cold-war','Medien und Bildung'],
  ['nuclear-program','Atomprogramm',6,'college','cold-war','Medien und Bildung'],
  ['central-intelligence','Zentraler Nachrichtendienst',3,'uneducated','modern','Medien und Bildung','caribbean-skies'],
  ['forest-school','Waldschule',5,'high-school','world-wars','Medien und Bildung','return-to-nature'],

  ['tourist-port','Touristenhafen',5,'uneducated','cold-war','Tourismus'],
  ['beach-villa','Strandvilla',1,'high-school','cold-war','Tourismus'],
  ['cabana-village','Cabana-Dorf',2,'uneducated','cold-war','Tourismus'],
  ['motel','Motel',2,'uneducated','cold-war','Tourismus'],
  ['hotel','Hotel',4,'uneducated','cold-war','Tourismus'],
  ['souvenir-shop','Souvenirladen',2,'uneducated','cold-war','Tourismus'],
  ['tour-office','Touristenbüro',3,'uneducated','cold-war','Tourismus'],
  ['ancient-ruins','Antike Ruinen',4,'uneducated','cold-war','Tourismus'],
  ['ethnic-enclave','Ethnische Enklave',4,'uneducated','cold-war','Tourismus'],
  ['airport','Flughafen',6,'high-school','modern','Tourismus'],
  ['economy-hotel','Economy-Hotel',6,'uneducated','modern','Tourismus'],
  ['family-resort','Familienresort',4,'uneducated','modern','Tourismus'],
  ['luxury-hotel','Luxushotel',4,'uneducated','modern','Tourismus'],
  ['skyscraper-hotel','Wolkenkratzerhotel',6,'uneducated','modern','Tourismus'],
  ['cruise-ship','Kreuzfahrtschiff',4,'uneducated','modern','Tourismus'],
  ['balloon-tours','Ballonfahrten',4,'uneducated','cold-war','Tourismus','caribbean-skies'],
  ['ticket-booth','Ticketschalter',2,'uneducated','cold-war','Tourismus','festival'],
  ['capsule-hotel','Kapselhotel',5,'uneducated','cold-war','Tourismus','new-frontiers'],
  ['campsite','Campingplatz',1,'uneducated','cold-war','Tourismus','return-to-nature'],

  ['chapel','Kapelle',2,'high-school','colonial','Öffentliche Dienste'],
  ['grocery','Lebensmittelladen',4,'uneducated','colonial','Öffentliche Dienste'],
  ['church','Kirche',3,'high-school','world-wars','Öffentliche Dienste'],
  ['clinic','Klinik',2,'college','world-wars','Öffentliche Dienste'],
  ['fire-station','Feuerwache',4,'high-school','world-wars','Öffentliche Dienste'],
  ['cathedral','Kathedrale',4,'college','cold-war','Öffentliche Dienste'],
  ['hospital','Krankenhaus',4,'college','cold-war','Öffentliche Dienste'],
  ['asylum','Irrenanstalt',6,'college','cold-war','Öffentliche Dienste'],
  ['garbage-dump','Mülldeponie',3,'uneducated','cold-war','Öffentliche Dienste'],
  ['shopping-mall','Einkaufszentrum',8,'uneducated','modern','Öffentliche Dienste'],
  ['waste-treatment','Müllaufbereitungsanlage',4,'high-school','modern','Öffentliche Dienste'],
  ['rehab-center','Rehabilitationszentrum',5,'college','modern','Öffentliche Dienste','spitter'],
  ['beauty-farm','Schönheitsfarm',5,'high-school','modern','Öffentliche Dienste','spitter'],
  ['drone-home-delivery','Drohnen-Hauslieferung',6,'uneducated','modern','Öffentliche Dienste','caribbean-skies'],
  ['snake-oil-salesman','Quacksalber',3,'uneducated','colonial','Öffentliche Dienste','going-viral'],
  ['isolation-center','Isolationszentrum',3,'high-school','colonial','Öffentliche Dienste','going-viral'],
  ['healing-howitzer','Heilende Haubitze',3,'high-school','world-wars','Öffentliche Dienste','going-viral'],
  ['mobile-doctor-squad','Mobiles Ärzteteam',3,'college','cold-war','Öffentliche Dienste','going-viral'],
  ['colossal-hospital','Kolossales Krankenhaus',8,'college','modern','Öffentliche Dienste','going-viral'],
  ['dolphin-therapy','Delfintherapie',6,'high-school','modern','Öffentliche Dienste','tropican-shores'],
  ['marine-cleanup','Meeresreinigungsstation',6,'high-school','modern','Öffentliche Dienste','tropican-shores'],
  ['herbalist','Kräuterkundiger',1,'high-school','colonial','Öffentliche Dienste','return-to-nature'],
  ['food-stall','Imbissstand',1,'uneducated','world-wars','Öffentliche Dienste','return-to-nature'],
  ['magazine-stand','Zeitschriftenstand',1,'uneducated','colonial','Öffentliche Dienste','return-to-nature'],
  ['outdoor-gym','Freiluft-Fitnessstudio',1,'uneducated','world-wars','Öffentliche Dienste','return-to-nature'],
  ['wayside-shrine','Wegschrein',1,'uneducated','colonial','Öffentliche Dienste','return-to-nature'],

  ['guard-tower','Wachturm',3,'uneducated','colonial','Militär'],
  ['fort','Fort',8,'uneducated','colonial','Militär'],
  ['pirate-cove','Piratenbucht',4,'uneducated','colonial','Militär'],
  ['watchtower','Beobachtungsturm',3,'uneducated','world-wars','Militär'],
  ['barracks','Kaserne',8,'uneducated','world-wars','Militär'],
  ['army-base','Militärbasis',2,'uneducated','world-wars','Militär'],
  ['commando-garrison','Kommandogarnison',6,'high-school','world-wars','Militär'],
  ['security-checkpoint','Sicherheitskontrollpunkt',1,'uneducated','cold-war','Militär'],
  ['aircraft-carrier','Flugzeugträger',4,'uneducated','cold-war','Militär'],
  ['spy-academy','Spionageakademie',3,'college','cold-war','Militär'],
  ['overwatchtower','Überwachungsturm',5,'uneducated','modern','Militär'],
  ['defense-hq','Verteidigungshauptquartier',5,'college','modern','Militär'],
  ['drone-command','Drohnenkommando',4,'high-school','modern','Militär'],
  ['cyber-operations-center','Cyberoperationszentrum',4,'college','modern','Militär'],
  ['spaceport-complex','Weltraumbahnhof',8,'college','cold-war','Militär','new-frontiers'],
  ['crew-cabin-assembly','Besatzungskabinen-Montage',4,'high-school','cold-war','Militär','new-frontiers'],
  ['cargo-hold-assembly','Frachtraum-Montage',4,'high-school','cold-war','Militär','new-frontiers'],
  ['fuel-tank-assembly','Treibstofftank-Montage',4,'high-school','cold-war','Militär','new-frontiers'],
  ['rocket-engine-assembly','Raketentriebwerk-Montage',4,'high-school','cold-war','Militär','new-frontiers'],
  ['medical-checkpoint','Medizinischer Kontrollpunkt',1,'uneducated','cold-war','Militär','going-viral'],

  ['palace','Palast',4,'uneducated','colonial','Regierung'],
  ['dungeon','Verlies',4,'uneducated','colonial','Regierung'],
  ['trade-institute','Handelsinstitut',4,'college','world-wars','Regierung','llama'],
  ['police-station','Polizeistation',4,'uneducated','world-wars','Regierung'],
  ['prison','Gefängnis',6,'high-school','world-wars','Regierung'],
  ['immigration-office','Einwanderungsbehörde',2,'college','world-wars','Regierung'],
  ['customs-office','Zollamt',5,'college','world-wars','Regierung'],
  ['ministry','Ministerium',5,'uneducated','world-wars','Regierung'],
  ['bank','Bank',4,'college','world-wars','Regierung'],
  ['corruption-agency','Antikorruptionsbehörde',4,'high-school','world-wars','Regierung','lobbyistico'],
  ['courthouse','Gericht',3,'college','cold-war','Regierung'],
  ['ministry-information','Informationsministerium',10,'college','cold-war','Regierung'],
  ['police-blimp','Polizeiluftschiff',4,'high-school','modern','Regierung'],
  ['tropocoin-farm','Tropocoin-Farm',4,'college','modern','Regierung'],
  ['office','Bürogebäude',5,'college','modern','Regierung']
];

export const WORKFORCE_BUILDINGS: Building[] = rows.map(([id,name,workers,education,availableFrom,category,dlc='base']) => ({
  id,name,icon:'•',category,dlc,workers,education,availableFrom,kind:'infrastructure',stage:99,dataStatus:'verified',
  source:'Tropico Wiki: Zeitalter, Arbeitsplätze und Bildungsgrad bestätigt',
  modes:[{id:'standard',name:'Standard',inputs:{},outputs:{}}]
}));
